### ISSUE TITLE
ProfilesRNS should not require the creation of a sysadmin user

### ISSUE THREAD

**Issue by jestill** [ProfilesRNS/ProfilesRNS#109]
Installation of Profiles requires the creation of a user with sysadmin privileges in the code at https://github.com/ProfilesRNS/ProfilesRNS/blob/master/Database/ProfilesRNS_CreateAccount.sql  This seems like an unnecessary security risk.

The code even includes a default password of _Password1234_, that could make it into production systems if installers are not careful.

I would like to be able to install and run Profiles without a sysadmin user account being required by the software. The default password should also be removed so that the SQL code will fail instead of creating a sysadmin user with such a risky password.

**Comment by nicholaswilliambrown** [comment]
I agree that this is a security concern. It is not necessary to create a sysadmin user. I'll update the script to only grant the required permissions.
