### ISSUE TITLE
ORNG gadget metadata returned in search results

### ISSUE THREAD

**Issue by nicholaswilliambrown** [ProfilesRNS/ProfilesRNS#168]
On search everything page, search for 'SlideShare' and the slideshare profile (App ID, link to xml etc) is returned. This shouldn't be searchable data.

**Comment by EricMeeks** [comment]
This is coming from the RDF. Hand grenade solution is to go into [Ontology.].[DataMap] and remove the rows with [ORNG.].[vwAppPersonData] in the Map Table column.
More surgical solution is to change the [ORNG.].[vwAppPersonData] to only expose the data you want to expose. I think that’s the fix anyway, our instance might be different.

We considered creating some mechanism for flagging which data we wanted to be exposed versus not exposed but never built anything. Would not be hard to do, just need to figure out what would make sense for people.

Eric

**Comment by nicholaswilliambrown** [comment]
I'm just changing the search weight for the data from [ORNG.].[vwAppPersonData] to 0. The nodes are still accessible if you really know where to look for them, but are not returned on search results. 

Nick
