### ISSUE TITLE
Altmetric Badges

### ISSUE THREAD

**Issue by nicholaswilliambrown** [ProfilesRNS/ProfilesRNS#87]
Add Altmetric links to publication lists,

**Comment by anirvan** [comment]
UCSF has used Altmetric badges (https://www.altmetric.com/products/altmetric-badges/) — talk to me or Eric Meeks about our experience using that platform.

**Comment by nicholaswilliambrown** [comment]
I spoke to Eric about the Altmetric badges a few weeks ago. We are planning to use the UCSF code with a couple of small modifications.
